# Generated by Django 4.2.7 on 2025-10-22 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другое')], max_length=1)),
                ('birth_date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('hobbies', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('single', 'В активном поиске'), ('dating', 'Встречаюсь'), ('married', 'Женат/Замужем'), ('complicated', 'Все сложно'), ('not_looking', 'Не ищу отношения')], default='single', max_length=20)),
                ('likes_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('privacy_settings', models.CharField(default='public', max_length=10)),
                ('show_online_status', models.BooleanField(default=True)),
                ('allow_messages', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_online', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_photos/')),
                ('is_main', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='users.userprofile')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
